main:
  - identifier: home
    name: Home
    url: /
    weight: 10
  - identifier: about
    name: About us
    url: /about/
    weight: 20
  - identifier: members
    name: Members
    url: /about/members/
    weight: 25
  - identifier: achievements
    name: Achievements
    url: /achievements/
    weight: 30
  - identifier: news
    name: News
    url: /news/
    weight: 40
  - identifier: resources
    name: Resources
    url: /resources/
    weight: 50
  - identifier: community-partners
    name: Sponsors
    url: /community-partners/
    weight: 60

footer:
  - identifier: about
    name: About Us
    url: /about/
    weight: 10
  - identifier: members
    name: Members
    url: /about/members/
    weight: 15
  - identifier: news
    name: News
    url: /news/
    weight: 20
  - identifier: resources
    name: Resources
    url: /resources/
    weight: 30
  - identifier: community-partners
    name: Sponsors
    url: /community-partners/
    weight: 40
