main:
  - identifier: home
    name: Home
    url: /
    weight: 10
  - identifier: conocenos
    name: About Us
    url: /conocenos/
    weight: 20
  - identifier: community-partners
    name: Sponsors
    url: /community-partners/
    weight: 60

footer:
  - identifier: conocenos
    name: About Us
    url: /conocenos/
    weight: 10
  - identifier: community-partners
    name: Sponsors
    url: /community-partners/
    weight: 30
