main:
  - identifier: init
    name: Home
    url: /
    weight: 10
  - identifier: about
    name: About us
    url: /about/
    weight: 20

footer:
  - identifier: about
    name: About Us
    url: /about/
    weight: 10
