main:
  - identifier: init
    name: Inicio
    url: /
    weight: 10
  - identifier: about
    name: Sobre nosotros
    url: /about/
    weight: 20
  - identifier: achievementsw
    name: Logros
    url: /achievements/
    weight: 30
  - identifier: news
    name: Noticias
    url: /news/
    weight: 40
  - identifier: resources
    name: Recursos
    url: /resources/
    weight: 50
  - identifier: community-partners
    name: Patrocinadores
    url: /community-partners/
    weight: 60
  - identifier: contact
    name: Contacto
    url: /contact/
    weight: 70
  - identifier: otherlinks
    pre: dropdown
    name: Otros enlaces
    weight: 90

otherlinks:
  - identifier: discord
    pre: /images/logos/discord.svg
    name: Discord
    url: https://discord.gg/gEbbJrzEYZ
    weight: 10
  - identifier: github
    pre: /images/logos/github.svg
    name: Github
    url: https://github.com/algoritmiaUS
    weight: 20
  - identifier: linkedin
    pre: /images/logos/linkedin.svg
    name: LinkedIn
    url: https://www.linkedin.com/company/club-de-algoritmia-universidad-de-sevilla
    weight: 30
  - identifier: youtube
    pre: /images/logos/youtube.svg
    name: Youtube
    url: https://www.youtube.com/@ClubAlgoritmiaUS
    weight: 40
  - identifier: unete
    pre: /images/logos/unete.svg
    name: Únete al CAUS!
    url: https://forms.gle/mQ9rsEGQURT6bza97
    weight: 50
  - identifier: dar-charlas
    pre: /images/logos/presentation.svg
    name: Dar Charlas
    url: https://forms.gle/yY9WpbA6Lof41ufa7
    weight: 60
  - identifier: feedback-caus
    pre: /images/logos/feedback.svg
    name: Feedback (Sesiones)
    url: https://forms.gle/bP9Jc81q4Hes1ZoN6
    weight: 70
  - identifier: archivo-sesiones
    name: Archivo de Sesiones
    url: https://drive.google.com/drive/folders/1uCZkV2LYut2omt07VdXgtjm6L0qgjgZR?usp=drive_link
    weight: 80

footer:
  - identifier: about
    name: Sobre nosotros
    url: /about/
    weight: 10
  - identifier: news
    name: Noticias
    url: /news/
    weight: 20
  - identifier: resources
    name: Recursos
    url: /resources/
    weight: 30
  - identifier: community-partners
    name: Patrocinadores
    url: /community-partners/
    weight: 40
  - identifier: contact
    name: Contacto
    url: /contact/
    weight: 50
