main:
  - identifier: home
    name: Inicio
    url: /
    weight: 10
  - identifier: conocenos
    name: Conócenos
    url: /conocenos/
    weight: 20
  - identifier: achievements
    name: Logros
    url: /achievements/
    weight: 30
  - identifier: news
    name: Noticias
    url: /news/
    weight: 40
  - identifier: resources
    name: Recursos
    url: /resources/
    weight: 50
  - identifier: community-partners
    name: Patrocinadores
    url: /community-partners/
    weight: 60

footer:
  - identifier: conocenos
    name: Conócenos
    url: /conocenos/
    weight: 10
  - identifier: news
    name: Noticias
    url: /news/
    weight: 20
  - identifier: resources
    name: Recursos
    url: /resources/
    weight: 30
  - identifier: community-partners
    name: Patrocinadores
    url: /community-partners/
    weight: 40
