main:
  - identifier: init
    name: Home
    url: /
    weight: 10
  - identifier: about
    name: About us
    url: /about/
    weight: 20
  - identifier: contact
    name: Contact
    url: /contact/
    weight: 40

footer:
  - identifier: about
    name: About Us
    url: /about/
    weight: 10
  - identifier: contact
    name: Contact
    url: /contact/
    weight: 20
