tags:
  adabyron: "AdaByron"
  complicaus: "CompliCAUS"
  competitions: "Competiciones"
  elections: "Elecciones"
  events: "Eventos"
  math-series: "Serie Matemáticas"
  news: "Noticias"
  talks: "Charlas"
categories:
  events: "Eventos"
  news: "Noticias"
