name: Enforce WebP Images Only

on:
  pull_request:

jobs:
  check-image-formats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Check for forbidden image formats
        run: |
          FORBIDDEN_FILES=$(find . -type f \( \
            -iname "*.jpg" -o \
            -iname "*.jpeg" -o \
            -iname "*.png" \
          \) -not -path "./.git/*")

          if [ -n "$FORBIDDEN_FILES" ]; then
            echo "::error::Only .webp images are allowed."
            echo "$FORBIDDEN_FILES"
            exit 1
          fi

          echo "All checks passed!"
